# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d8f7f1a0a734974d68c1fc095c04ee466a9a4fe2691b46082fbddafe402f91cfa51d31113c8968fe26182b6cc9b329210dc3466cae683cffe8d296e29822db0

test:
  secret_key_base: fcac527dd8977b06ad9084fbd4df3d827532dc1e08e09d2028e27ea14c24245bf396bd778b9467e9541ca126d9751c2ca269e5db34f8191542a6db1539499a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
